### ISSUE TITLE
Cleanup/refactoring

### ISSUE THREAD

**Issue by mikalai-sauchanka** [crushcat/epam-tasks-app2#1]
Clean up/refactor your code base by:
1. removing files/folder/code not relevant to the task
2. removing code duplications (if any)
3. logically split js code onto files (if applicable), don't pollute global object (front end)
4. update the js code to follow [Douglas Crockford's code conventions](http://javascript.crockford.com/code.html). Create/download a config file for JSLint/JSHint. Also remove unnecessary empty lines (if any), to make the code look cleaner.
5. use ECMA6 whenever possible

**Comment by crushcat** [comment]
1. removing files/folder/code not relevant to the task - https://github.com/crushcat/epam-tasks-app2/pull/2
2. removing code duplications (if any) - https://github.com/crushcat/epam-tasks-app2/pull/2
3. logically split js code onto files (if applicable), don't pollute global object (front end) - https://github.com/crushcat/epam-tasks-app2/pull/2
4. update the js code to follow Douglas Crockford's code conventions. Create/download a config file for JSLint/JSHint. Also remove unnecessary empty lines (if any), to make the code look cleaner. - https://github.com/crushcat/epam-tasks-app2/pull/2
5. use ECMA6 whenever possible - https://github.com/crushcat/epam-tasks-app2/pull/2

**Comment by mikalai-sauchanka** [comment]
https://github.com/crushcat/epam-tasks-app2/pull/2
